# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a92f034b0921803ca9ddce6793d6acec89738c2bfb0570ee08473d781b939886d1c46b9abec925427e5ff7055c321829102df93a5ae90a153f6df1e62bba1aaa

test:
  secret_key_base: a86d99215dc7c67abcf5ad2ee6705cc7371b6c029918f1ca997845c2f5246d865b77d5e140f370d5a499ba5ced2af91ba67d5764f44f56529079df331f21de8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
